name: API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install Newman and HTML reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Install dependencies
      run: npm install

    - name: Start API server
      run: |
        docker-compose -f docker-compose.${{ matrix.environment }}.yml up -d
        echo "Waiting for server to start..."
        sleep 15  # Give the server time to start
        docker-compose -f docker-compose.${{ matrix.environment }}.yml ps

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run API tests
      run: |
        newman run coffee_api.postman_collection.json \
          -e coffee_api_${{ matrix.environment }}.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export reports/${{ matrix.environment }}_report.html \
          --reporter-htmlextra-title "Coffee API Tests - ${{ matrix.environment }} Environment" \
          --reporter-htmlextra-darkTheme \
          --reporter-htmlextra-showMarkdownLinks \
          --reporter-htmlextra-timezone "UTC"

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-${{ matrix.environment }}
        path: reports/
        retention-days: 7

    - name: Stop API server
      if: always()
      run: docker-compose -f docker-compose.${{ matrix.environment }}.yml down

    - name: Check test results
      if: failure()
      run: |
        echo "Tests failed for environment: ${{ matrix.environment }}"
        exit 1 